name: IGS-1

on: 
  workflow_dispatch: # allow for manual execution
  push:


jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
